# Generated by Django 5.0.7 on 2024-07-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptinglang',
            name='type',
            field=models.CharField(choices=[('Js', 'JavaScript'), ('JSX', 'Javascript_Extension'), ('Rb', 'Ruby'), ('JAVA', 'Java'), ('Py', 'Python')], max_length=4),
        ),
    ]
