# Generated by Django 5.0.7 on 2024-07-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_scriptinglang_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptinglang',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
